import { Inter } from "next/font/google";
import "./globals.css";
// import { ThemeProvider } from "next-themes";
import Header from "../components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "../components/theme-provider";
import { dark } from "@clerk/themes";
import { Toaster } from "sonner";

const inter = Inter({subsets:["latin"]});

export const metadata = {
  title: "AI Career Assistant",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{
      baseTheme:dark
    }}> 
    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${inter.className} `}>

      <ThemeProvider 
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
            >

            {/* Header */}
            <Header/>
           <main className="min-h-screen">{children}</main>
           <Toaster richColors/>
            {/*footer  */}
            <footer className="bg-muted/50 py-12">
              <div className="container mx-auto text-center px-4 text-gray-200">
                <p>made by @ S&P Brothers</p>
              </div>
            </footer>
            </ThemeProvider>
        
          
      </body>
    </html>
  </ClerkProvider>
  );
}
